version: '3.1'
services:
  housepass-mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
    - "27017:27017"
    volumes:
    - D:/Mongodb/data/db:/data/db
    - D:/Mongodb/data/configdb:/data/configdb
    restart: always     
      